version: '3.3'

volumes:
  pg_data:
  static:
  media:
  
services:
  db:
    image: postgres:13.10
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/pg_data
  
  backend:
    image: flyshy/foodgram_backend
    env_file: .env
    volumes:
      - static:/app/backend_static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: flyshy/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - 8080:80
    volumes:
      - media:/media/
      - static:/static/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/  
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
